### ISSUE TITLE
파이썬을 활용한 시계열 데이터 분석 A-Z 올인원 패키지 Online. 관련 질문 드립니다.

### ISSUE THREAD

**Issue by hongym7** [cheonbi/OnlineTSA#2]
2.2.2 시계열 데이터 준비 에서
one-step ahead cross-validation two-step ahead cross-validation 모델을 앙상블해서 쓰는건 어떨까요?

**Comment by cheonbi** [comment]
네 그런방식도 이미 많이 사용되고있습니다~
해봐야하는 아이디어라고 봅니다!

2021년 10월 1일 (금) 오후 3:36, Yongman Hong ***@***.***>님이 작성:
